# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fdc5508a5d4f7a39a732f5b299b3fa4a29f2f1ec7c563340408ea01200c70a2d912c3dc22b3b7fd171f099796b85edaafbaca006e909347cf7c5ac20632b6b2

test:
  secret_key_base: 352256db49c69e7e6ed978aa4ffe6d5edb6a613622a4f7c7856f4913d00fd6243201321d7c74edbfa0ec31ad37da2e3fa3f67279e15c65199a8d216831013b49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
